AWSTemplateFormatVersion: "2010-09-09"

Description: CloudFront Stack

Parameters:
  CertificateArn:
    Type: String
  AlternativeDomainName:
    Type: String

Resources:
  OAC: 
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig:
        Description: Access Control
        Name: OAC
        # ドメインオリジンと同じもの（今回はS3）
        OriginAccessControlOriginType: s3
        # 常に署名する
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig: 
        # 代替ドメイン名を指定
        Aliases:
          - !Ref AlternativeDomainName
        Origins:
          - DomainName: !ImportValue S3
            Id: S3
            OriginAccessControlId: !GetAtt OAC.Id
            # OriginShield:
              # Enabled: false
              # OriginShieldRegion: ap-northeast-1
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior: 
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: S3
          # マネージドキャッシュポリシーのCachingOptimizedを使用
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        Enabled: true
        PriceClass: PriceClass_200
        ViewerCertificate:
          # ACMを設定
          AcmCertificateArn: !Ref CertificateArn
          # セキュリティポリシー
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

Outputs:
  CloudFrontID:
    Value: !Ref CloudFront
    Export: 
      Name: CloudFrontID